### ISSUE TITLE
panic full crash

### ISSUE THREAD

**Issue by adrianlzt** [adrianlzt/piclimbing#10]
```
panic: runtime error: index out of range [-1]

goroutine 12 [running]:
github.com/adrianlzt/piclimbing/backend/strength.(*Strength).Calculator(0x869d180, 0x6d1c7b1a, 0x3ff47068, 0x87b9e134, 0xc0348d73, 0x4af5a8c2, 0x97, 0x13db8b8, 0x13b80e3, 0x0, ...)
        /home/adrian/Documentos/raspberry/entrenamiento_escalada/app/strength/strength.go:547 +0x950
github.com/adrianlzt/piclimbing/backend/strength.(*Strength).Coach(0x869d180, 0x8452600, 0x8452380, 0x8452640)
        /home/adrian/Documentos/raspberry/entrenamiento_escalada/app/strength/strength.go:417 +0x120
created by github.com/adrianlzt/piclimbing/backend/strength.(*Strength).RunStrength
        /home/adrian/Documentos/raspberry/entrenamiento_escalada/app/strength/strength.go:205 +0x1d8
```

**Comment by adrianlzt** [comment]
``calculateEnd`` should be refactored
